meal_plans/urls.py
from django.urls import path
from meal_plans.views import (
    MealPlanListView,
    MealPlanCreateView,
    MealPlanDeleteView,
    MealPlanDetailView,
    MealPlanUpdateView,
)

urlpatterns = [
    path("", MealPlanListView.as_view(), name="meal_plans_list"),
    path(
        "create/",
        MealPlanCreateView.as_view(),
        name="meal_plans_create",
    ),
    path(
        "<int:pk>/edit/",
        MealPlanUpdateView.as_view(),
        name="meal_plans_update",
    ),
    path(
        "<int:pk>/delete/",
        MealPlanDeleteView.as_view(),
        name="meal_plans_delete",
    ),
    path(
        "<int:pk>/",
        MealPlanDetailView.as_view(),
        name="meal_plans_detail",
    ),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("meal_plans/", include("meal_plans.urls")),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDeleteView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

meal_plans/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


class MealPlan(models.Model):
    name = models.CharField(max_length=120)
    date = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="meal_plans",
        on_delete=models.CASCADE,
        null=True,
    )
    recipes = models.ManyToManyField("recipes.Recipe", related_name="recipes")

    def __str__(self):
        return self.name + " on " + str(self.date)

meal_plans/forms.py
from django.forms import ModelForm
from meal_plans.models import MealPlan

# mealPlanForm
class MealPlanForm(ModelForm):
    class Meta:
        model = MealPlan
        fields = [
            "name",
            "recipes",
        ]


# mealPlanDeleteForm
class MealPlanDeleteForm(ModelForm):
    class Meta:
        model = MealPlan
        fields = [
            "name",
            "recipes",
        ]

meal_plans/views.py
from django.shortcuts import redirect, render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from meal_plans.models import MealPlan
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from meal_plans.forms import MealPlanForm, MealPlanDeleteForm


class MealPlanListView(LoginRequiredMixin, ListView):
    model = MealPlan
    template_name = "meal_plans/list.html"
    paginate_by = 10

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanCreateView(LoginRequiredMixin, CreateView):
    model = MealPlan
    template_name = "meal_plans/create.html"
    fields = ["name", "recipes"]

    def form_valid(self, form):
        plan = form.save(commit=False)
        plan.owner = self.request.user
        plan.save()
        form.save_m2m()
        return redirect("meal_plans_detail", pk=plan.id)


class MealPlanDetailView(LoginRequiredMixin, DetailView):
    model = MealPlan
    template_name = "meal_plans/detail.html"
    fields = ["name", "date", "recipes.Recipe"]

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanUpdateView(LoginRequiredMixin, UpdateView):
    model = MealPlan
    template_name = "meal_plans/edit.html"
    fields = ["name", "recipes"]

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

    def get_success_url(self) -> str:
        return reverse_lazy("meal_plans_detail", args=[self.object.id])


class MealPlanDeleteView(LoginRequiredMixin, DeleteView):
    model = MealPlan
    template_name = "meal_plans/delete.html"
    sucess_url = reverse_lazy("meal_plan_list")

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

    def get_success_url(self) -> str:
        return reverse_lazy("meal_plans_list")


# cerate forms
from meal_plans.forms import MealPlanForm, MealPlanDeleteForm
from meal_plans.models import MealPlan

meal_plans/templates/meal_plans/create.html
{% extends 'base.html' %}

{% block content %}
  <main class="recipe-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Create</button>
      </div>
    </form>
  </main>
  {% endblock content %}

meal_plans/templates/meal_plans/delete.html
{% extends 'base.html' %}
{% block content %}
  <main>
    <form method="post">
      {% csrf_token %}
      <p>Are you sure you want to delete "{{ recipe }}"?</p>
      {{ form.as_p }}
      <div class="control">
        <button class="button">Delete</button>
      </div>
    </form>
  </main>
  {% endblock content %}

meal_plans/templates/meal_plans/detail.html
{% extends 'base.html' %}

{% block content %}
{% load markdownify %}
  <main class="recipe-detail">
    <div>
      <a href="{% url 'meal_plans_update' mealplan.id %}">Edit</a>
      <a href="{% url 'meal_plans_delete' mealplan.id %}">Delete</a>
    </div>
    <h2>
    Recipes for {{mealplan.name}} on {{mealplan.date}}
    </h2>
    {% for recipe in object.recipes.all %}
    <p>
    <a href="{% url 'recipe_detail' recipe.pk %}">{{recipe.name}}</a>
    </p>
    {% endfor %}
  </main>
{% endblock content %}

meal_plans/templates/meal_plans/edit.html
{% extends 'base.html' %}
{% block content %}
    <main class="recipe-form">
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="control">
          <button class="button">Create</button>
        </div>
      </form>
    </main>
{% endblock content %}

meal_plans/templates/meal_plans/list.html
{% extends 'pagination.html' %}

{% block content %}
  <div>
      <a href="{% url 'meal_plans_create' %}">Create</a>
  </div>
  <main class="recipe-grid">
    {% for mealplan in mealplan_list%}
      <div class="recipe-card">
          <h2 class="recipe-card-title">
            <a href="{% url 'meal_plans_detail' mealplan.id %}">{{mealplan.name}} </a>
          </h2>
          {% for recipe in mealplan.recipes.all %}
            <p>
                <a href="{% url "recipe_detail" recipe.pk %}">{{ recipe.name }}</a>
            </p>
          {% endfor %}
      </div>
      {% empty %}
        <div>
          <h1>No meals planned yet.</h1>
          <p>
            Want to 
            <a href="{% url 'meal_plans_create' %}">add</a>
            a new one?
          </p>
        </div>
    {% endfor %}
  </main>
{% endblock content %}